name: python-tiledbsoma-ml past tiledbsoma compat # Latest tiledbsoma version covered by another workflow

on:
  pull_request:
    branches: ["*"]
    paths-ignore:
      - "scripts/**"
  push:
    branches: [main]
    paths-ignore:
      - "scripts/**"

jobs:
  unit_tests:
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-latest", "macos-latest"]
        python-version: ["3.9", "3.10", "3.11", "3.12"]
        pkg-version:
          - "tiledbsoma~=1.9.0 'numpy<=2.0.0'"
          - "tiledbsoma~=1.10.0 'numpy<=2.0.0'"
          - "tiledbsoma~=1.11.0"
          - "tiledbsoma~=1.12.0"
          - "tiledbsoma~=1.13.0"
          - "tiledbsoma~=1.14.0"
        exclude: # TODO: remove mac-os/3.12 exclusion when tiledbsoma supports it
          - python-version: 3.12
            os: macos-latest

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip

      - name: Install prereqs
        run: |
          pip install --upgrade pip pytest setuptools
          pip install ${{ matrix.pkg-version }} .

      - name: Run tests
        run: pytest -v tests
