name: Release
on:
  release:
    types: [ 'published' ]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Setup Python
        uses: actions/setup-python@v5
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build package
        run: pip install build && python -m build && ls -l dist
      - name: Publish package distributions to Test PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        continue-on-error: true
        with:
          repository_url: https://test.pypi.org/legacy/
      - name: Publish package distributions to PyPI
        if: "!github.event.release.prerelease"
        uses: pypa/gh-action-pypi-publish@release/v1
