name: Release
on:
  release:
    types: [ 'published' ]

jobs:
  pypi-publish:
    name: upload release to PyPI
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      id-token: write
    steps:
      - name: Setup Python
      - uses: actions/setup-python@v2
      - name: Checkout
      - uses: actions/checkout@v2
      - name: Build package
      - run: pip install build && python -m build && ls -l dist
      - name: Publish package distributions to PyPI
        if: "!github.event.release.prerelease"
        uses: pypa/gh-action-pypi-publish@release/v1
